In [ ]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

import tensorflow as tf

In [ ]:
df = pd.read_csv("otu.csv")

/usr/local/lib/python3.8/dist-packages/IPython/core/interactiveshell.py:3326: DtypeWarning: Columns (0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,2

In [ ]:
df.head()

Sample1  Sample2 Sample3 Sample4  Sample5 Sample6 Sample7 Sample8 Sample9  \
0     left     left    left    left     left    left    left    left    left   
1  0.33364  0.62579       0       0  0.56233       0       0       0       0   
2  0.33364  0.62579       0       0  0.56233       0       0       0       0   
3  0.33364  0.62579       0       0  0.56233       0       0       0       0   
4  0.33364  0.62579       0       0  0.56233       0       0       0       0   

  Sample10  ... Sample262 Sample263 Sample264 Sample265 Sample266 Sample267  \
0     left  ...     right     right     right     right     right     right   
1        0  ...         0   6.11234         0         0         0         0   
2        0  ...         0   6.11234         0         0         0         0   
3        0  ...         0   6.10627         0         0         0         0   
4        0  ...         0   6.10627         0         0         0         0   

  Sample268 Sample269 Sample270 Sample271  
0     right     right     right     right  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  

[5 rows x 271 columns]

In [ ]:
dft = df.transpose()
dft

0        1        2        3        4        5        6     \
Sample1     left  0.33364  0.33364  0.33364  0.33364  0.33364  0.33364   
Sample2     left  0.62579  0.62579  0.62579  0.62579  0.62579  0.62579   
Sample3     left        0        0        0        0        0        0   
Sample4     left        0        0        0        0        0        0   
Sample5     left  0.56233  0.56233  0.56233  0.56233  0.56233  0.56233   
...          ...      ...      ...      ...      ...      ...      ...   
Sample267  right        0        0        0        0        0        0   
Sample268  right        0        0        0        0        0        0   
Sample269  right        0        0        0        0        0        0   
Sample270  right        0        0        0        0        0        0   
Sample271  right        0        0        0        0        0        0   

              7        8        9     ... 3293 3294 3295 3296 3297 3298 3299  \
Sample1    0.33364  0.33364        0  ...    0    0    0    0    0    0    0   
Sample2    0.49776  0.49776  0.12802  ...    0    0    0    0    0    0    0   
Sample3          0        0        0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
Sample4          0        0        0  ...    0    0    0    0    0    0    0   
Sample5    0.49446  0.49446  0.06786  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
...            ...      ...      ...  ...  ...  ...  ...  ...  ...  ...  ...   
Sample267        0        0        0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
Sample268        0        0        0  ...    0    0    0    0    0    0    0   
Sample269        0        0        0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
Sample270        0        0        0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
Sample271        0        0        0  ...    0    0    0    0    0    0    0   

          3300 3301 3302  
Sample1      0    0    0  
Sample2      0    0    0  
Sample3    0.0  0.0  0.0  
Sample4      0    0    0  
Sample5    0.0  0.0  0.0  
...        ...  ...  ...  
Sample267  0.0  0.0  0.0  
Sample268    0    0    0  
Sample269  0.0  0.0  0.0  
Sample270  0.0  0.0  0.0  
Sample271    0    0    0  

[271 rows x 3303 columns]

In [ ]:
features = dft[dft.columns[1:]].values
expectedOutputs = dft[dft.columns[0]].values;

In [ ]:
features = features.astype(np.double)
features

array([[0.33364, 0.33364, 0.33364, ..., 0.     , 0.     , 0.     ],
       [0.62579, 0.62579, 0.62579, ..., 0.     , 0.     , 0.     ],
       [0.     , 0.     , 0.     , ..., 0.     , 0.     , 0.     ],
       ...,
       [0.     , 0.     , 0.     , ..., 0.     , 0.     , 0.     ],
       [0.     , 0.     , 0.     , ..., 0.     , 0.     , 0.     ],
       [0.     , 0.     , 0.     , ..., 0.     , 0.     , 0.     ]])

In [ ]:
expectedOutputs[expectedOutputs == 'left'] = 0
expectedOutputs[expectedOutputs == 'right'] = 1
expectedOutputs = expectedOutputs.astype(np.double)
expectedOutputs

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1.

In [ ]:
means = np.sum(features, axis=0) / np.size(features, 1)
reducedFeatures = np.delete(features, means == 0, 1)

reducedFeatures.shape

(271, 1387)

In [ ]:
scaler = StandardScaler()
reducedFeatures = scaler.fit_transform(reducedFeatures)

In [ ]:
featureTrain, featureTest, expectedTrain, expectedTest = train_test_split(reducedFeatures, expectedOutputs, test_size=0.2, random_state=7)
#featureTrain, featureTemp, expectedTrain, expectedTemp = train_test_split(features, expectedOutputs, test_size=0.4, random_state=12)
#featureValid, featureTest, expectedValid, expectedTest = train_test_split(featureTemp, expectedTemp, test_size=0.5, random_state=7)

In [ ]:
expectedTrain

array([1., 0., 0., 0., 1., 0., 0., 1., 1., 0., 1., 1., 0., 0., 0., 1., 0.,
       1., 0., 1., 0., 0., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 1., 0.,
       1., 0., 1., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 1., 0., 1., 0.,
       0., 1., 1., 1., 0., 0., 0., 1., 1., 0., 0., 0., 0., 1., 1., 0., 0.,
       1., 1., 0., 1., 1., 0., 1., 1., 0., 0., 1., 1., 1., 1., 1., 0., 1.,
       0., 1., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0., 1., 1., 1., 1., 1.,
       0., 1., 1., 0., 0., 1., 1., 0., 0., 1., 0., 0., 1., 0., 1., 0., 1.,
       0., 0., 0., 1., 0., 1., 0., 1., 0., 1., 0., 0., 0., 1., 1., 0., 0.,
       1., 1., 1., 0., 1., 0., 0., 1., 0., 1., 0., 1., 1., 1., 1., 0., 1.,
       1., 0., 1., 1., 1., 0., 0., 1., 0., 0., 1., 0., 0., 1., 0., 1., 0.,
       1., 1., 0., 1., 0., 1., 1., 1., 0., 1., 0., 0., 1., 1., 1., 0., 1.,
       1., 0., 1., 1., 1., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0., 0., 0.,
       1., 1., 0., 0., 0., 1., 0., 1., 0., 0., 1., 1.])

In [ ]:
tf.convert_to_tensor(featureTrain)
tf.convert_to_tensor(expectedTrain)
tf.convert_to_tensor(featureTest)
tf.convert_to_tensor(expectedTest)
expectedTrain

array([1., 0., 0., 0., 1., 0., 0., 1., 1., 0., 1., 1., 0., 0., 0., 1., 0.,
       1., 0., 1., 0., 0., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 1., 0.,
       1., 0., 1., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 1., 0., 1., 0.,
       0., 1., 1., 1., 0., 0., 0., 1., 1., 0., 0., 0., 0., 1., 1., 0., 0.,
       1., 1., 0., 1., 1., 0., 1., 1., 0., 0., 1., 1., 1., 1., 1., 0., 1.,
       0., 1., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0., 1., 1., 1., 1., 1.,
       0., 1., 1., 0., 0., 1., 1., 0., 0., 1., 0., 0., 1., 0., 1., 0., 1.,
       0., 0., 0., 1., 0., 1., 0., 1., 0., 1., 0., 0., 0., 1., 1., 0., 0.,
       1., 1., 1., 0., 1., 0., 0., 1., 0., 1., 0., 1., 1., 1., 1., 0., 1.,
       1., 0., 1., 1., 1., 0., 0., 1., 0., 0., 1., 0., 0., 1., 0., 1., 0.,
       1., 1., 0., 1., 0., 1., 1., 1., 0., 1., 0., 0., 1., 1., 1., 0., 1.,
       1., 0., 1., 1., 1., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0., 0., 0.,
       1., 1., 0., 0., 0., 1., 0., 1., 0., 0., 1., 1.])

In [ ]:
model1 = tf.keras.Sequential([
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dense(1, activation='sigmoid')
    ])

In [ ]:
model1.compile(optimizer=tf.keras.optimizers.SGD(learning_rate=0.01, momentum=0.7),
              loss=tf.keras.losses.BinaryCrossentropy(),
              metrics=['accuracy', 'AUC', tf.keras.metrics.TruePositives(), 
              tf.keras.metrics.TrueNegatives(), tf.keras.metrics.FalsePositives(),
              tf.keras.metrics.FalseNegatives()])

In [ ]:
model1.evaluate(featureTrain, expectedTrain)

7/7 [==============================] - 1s 4ms/step - loss: 0.7096 - accuracy: 0.5139 - auc: 0.5117 - true_positives_2: 57.0000 - true_negatives_2: 54.0000 - false_positives_2: 54.0000 - false_negatives_2: 51.0000


[0.7095993161201477,
 0.5138888955116272,
 0.5117455124855042,
 57.0,
 54.0,
 54.0,
 51.0]

In [ ]:
model1.fit(featureTrain, expectedTrain, batch_size=32, epochs=50)
#model.fit(featureTrain, expectedTrain, batch_size=16, epochs=50, validation_data=(featureValid, expectedValid))

Epoch 1/50
7/7 [==============================] - 1s 4ms/step - loss: 0.7352 - accuracy: 0.4907 - auc: 0.4144 - true_positives_9: 11.0000 - true_negatives_9: 95.0000 - false_positives_9: 13.0000 - false_negatives_9: 97.0000
Epoch 2/50
7/7 [==============================] - 0s 4ms/step - loss: 0.6736 - accuracy: 0.5926 - auc: 0.6102 - true_positives_9: 66.0000 - true_negatives_9: 62.0000 - false_positives_9: 46.0000 - false_negatives_9: 42.0000
Epoch 3/50
7/7 [==============================] - 0s 4ms/step - loss: 0.6365 - accuracy: 0.6898 - auc: 0.7728 - true_positives_9: 92.0000 - true_negatives_9: 57.0000 - false_positives_9: 51.0000 - false_negatives_9: 16.0000
Epoch 4/50
7/7 [==============================] - 0s 4ms/step - loss: 0.6087 - accuracy: 0.7731 - auc: 0.8526 - true_positives_9: 93.0000 - true_negatives_9: 74.0000 - false_positives_9: 34.0000 - false_negatives_9: 15.0000
Epoch 5/50
7/7 [==============================] - 0s 5ms/step - loss: 0.5809 - accuracy: 0.8056 - auc: 0

In [ ]:
mets = model1.evaluate(featureTest, expectedTest)
auc = mets[2];
tp = mets[3];
tn = mets[4];
fp = mets[5];
fn = mets[6];

sensitivity = tp / (tp + fn)
specificity = tn / (tn + fp)

print(f'AUC: {auc}')
print(f'sensitivity: {sensitivity}')
print(f'specificity: {specificity}')

2/2 [==============================] - 1s 5ms/step - loss: 1.0643 - accuracy: 0.7455 - auc: 0.7738 - true_positives_9: 21.0000 - true_negatives_9: 20.0000 - false_positives_9: 8.0000 - false_negatives_9: 6.0000
AUC: 0.773809552192688
sensitivity: 0.7777777777777778
specificity: 0.7142857142857143
